language: node_js
node_js:
- '6'
install:
- npm install
script: npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: mt.franchetto@gmail.com
  api_key:
    secure: Ykoq/ZrSs+cloFm8KSSxR6XkSQv+MXHmTMhMZcv9LJAvldm1PVbxE4UgLd5cIsodvkFQYpkKO5qbEv23+C4VSrF6qFJF54TPo33MYUJc7UiBuilXVKh+GuuLGwYF58P5upwextclwO4rj3rqLsmfSpjtWNtETa9iZVdcuFttIo1xQyf0ypAFDtoX2F6ir9vppLjz3vV4l/4v73hPTm5tneOV55uk9fraDyx5c+RPmU+vBAORZFzVBjPX+C68AE/Ge2qXmdqv4pSbc7PaZW2GsZFivp7VjyhJpDP7uWIrZR9XdScr6K8G1TmKqMWGv4HYOrYmL4FIfoZiEPGYb66kyg6UoQTMDhL+LEquDs2KjE2dyB+hij49HmFBcZc/RVFAv7bLXKfsmrof2loHteE4mr+Dm2WGvHXuhRlsO6lYeURwf53d22yADW9igEIfVuIaftqa7V4UGUGUJa3IGjG4pWt68oRJ0qSwVwYCihOOMWWXmIPQ70DQb4N99YC007g8wwEOQCI6KNmPFo72ym+gngQRRjjoCcvHcJv4VXcc5vrYinP7U0w0T9pPWozXwA+TYjr1k18PcxFVKT4Gr04RmJduxraA6TLmTWvPOZyO+v6ORtHz8sKHFurmPpeNgulVLNXSi4QK8dg5UYPRkf7HkTqSScRhf/fLz3KGqDQrhYQ=
  on:
    branch: master
    repo: mtfranchetto/smild
    tags: false
